base_voc = 'data/VOCtrainval_11-May-2012/VOCdevkit/VOC2012'
base_city = '../../dataset/cityscapes'
base_gtav = '../../dataset/gtav'
base_synthia = '../../dataset/syn/SYNTHIA_RAND_CITYSCPAES'
base_tusimple = '../../dataset/tusimple'
base_culane = '../../dataset/culane'
